runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpeg|jpg|css|js|ico))$
  static_files: todoUI/\1
  upload: todoUI/(.*)
- url: /(.*)
  static_files: todoUI/index.html
  upload: todoUI/index.html